### PR TITLE
yes

### PR DESCRIPTION
**Pull request by terryadavis**
no

### CODE REVIEW

**Comment by M-T3K** [comment]
This is quite unnecessary...

**Comment by terryadavis** [comment]
says the person who added a netvar

**Comment by M-T3K** [comment]
Excuse me if I'm missing your point, but all you're doing with this is change indentation and some comments, which he may have intentionally written that way because of personal preference / coding style. 
And Yes, I added a netvar that was missing in this base. Somebody might find it useful, specially beginners; but at least I added something to the code other than spaces.

Anyways, Mark will be the one who decides wether this is useful or not.

**Comment by terryadavis** [comment]
@M-T3K I changed some indentation that default VS does and I removed 5 useless variables when you can do PROCESS_ALL_ACCESS

**Pull request closed without merging**
