### PR TITLE
Skeleton ESP

### PR DESCRIPTION
**Pull request by czvpka**
Simple skeleton ESP with much bones! (not much, it's just my 1st skeleton esp :sob: I'll try later to add fingers and much more! :smile:)
image

### CODE REVIEW

**Comment by bighaxor** [comment]
The commits are too dirty try adding skeleton from the newist fork

**Comment by xbRead** [comment]
Good work, but this only works on some models. Newer rigged models look kinda weird i'll work on a fix then post it back here. https://i.imgur.com/FXDOFZg.jpg

**Comment by FADDD** [comment]
add aimbot :1st_place_medal:

**Comment by bighaxor** [comment]
@FADDD aimbot in a base lol.

**Comment by bighaxor** [comment]
Remake pull request with just adding skeleton esp

**Comment by czvpka** [comment]
Accidentially added something BAD to hooks.cpp, closing xd

**Pull request closed without merging**
