### PR TITLE
Update Enums.hpp

### PR DESCRIPTION
**Pull request by bighaxor**

### CODE REVIEW

**Comment by bighaxor** [comment]
No it's not needed I added them in the first place

**Comment by wi1h** [comment]
Okay, but they are needed (well if a glove changer is added, I guess). They're valid item definition indexes.

**Comment by bighaxor** [comment]
fuck it let me fully update the indexes

**Comment by bighaxor** [comment]
Pretty much the entire cheat is updated now

to do's

move all enums to enums.hpp
update Playerbones to all of them

**Comment by bighaxor** [comment]
no

**Pull request closed without merging**
