### PR TITLE
Add PaintTraverse hook and update signatures

### PR DESCRIPTION
**Pull request by baarsik**
Added empty PaintTraverse hook that validates current panel.
Also updated signatures.

### CODE REVIEW

**Comment by certmemer** [comment]
Why would you add that, d3d is far more efficient.

**Comment by baarsik** [comment]
Mainly because it will not overlay console. Moreover using D3D I had some issues with ESP - it was sometimes blinking.

**Comment by MarkHC** [comment]
I am working on a whole rewrite for this project. Not gonna merge anything right now.

Thanks though.

**Comment by skrrtskrrt** [comment]
Still working on it?

**Pull request closed without merging**
